# Generated by Django 4.0.1 on 2022-02-02 21:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(default=None, max_length=200, verbose_name='email')),
                ('invoince_type', models.BooleanField(default=False, verbose_name='Kurumsal Müşteri Fatura')),
                ('turkish_id', models.IntegerField(blank=True, default=None, null=True)),
                ('tax_id', models.IntegerField(blank=True, default=0, null=True)),
                ('tax_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('tax_surname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('tax_office', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('tax_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('invoince_address', models.TextField(default=None, max_length=500)),
            ],
            options={
                'verbose_name': 'Müşteri Bilgisi',
                'verbose_name_plural': 'Müşteri Bilgileri',
                'ordering': ['name', 'surname'],
            },
        ),
    ]
