# Generated by Django 4.0.1 on 2022-02-03 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Firma Personeli'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='invoince_address',
            field=models.TextField(default=None, max_length=500, verbose_name='Fatura Adresi'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='invoince_type',
            field=models.CharField(choices=[('B', 'Bireysel'), ('K', 'Kurumsal')], default=False, max_length=1, verbose_name='Fatura Tipi'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='tax_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='VKN No'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='tax_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Fatura Müşteri Adı'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='tax_office',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='tax_surname',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Fatura Müşteri Soyadı'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='tax_title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Firma Ünvanı'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='turkish_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='TC Kimlik No:'),
        ),
    ]
