# Generated by Django 4.0.1 on 2022-02-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customerinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuementName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(max_length=50, verbose_name='Ölçü Adı')),
            ],
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='tax_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='VKN No'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='turkish_id',
            field=models.IntegerField(blank=True, default='11111111111', null=True, verbose_name='TC Kimlik No:'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(choices=[('SALON', 'Salon Odası'), ('OO', 'Oturma Odası'), ('MUTFAK', 'Mutfak'), ('YO', 'Yatak Odası'), ('ÇOCUK O', 'Çocuk Odası'), ('Çalışma O', 'Çalışma Odası'), ('GIYINME ODASI', 'Giyinme Odası'), ('SINEMA ODASI', 'Sinema Odası'), ('KILER', 'Kiler'), ('MISAFIR ODASI', 'Misafir Odası')], max_length=15, verbose_name='Oda Adı')),
                ('curtain_type', models.CharField(choices=[('ZEBRA', 'Zebra Perde'), ('STOR', 'Stor Perde'), ('DIKEY', 'Dikey Perde'), ('Plicel', 'Plicel Perde'), ('KUMAS', 'Kumaş Perde'), ('TÜL', 'Tül Perde'), ('FON', 'Fon Perde'), ('GUNESLİK', 'Güneşlik Perde')], max_length=15, verbose_name='Perde Tipi')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerinfo', verbose_name='Müşteri IDs')),
                ('measurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.measuementname', verbose_name='Ölçü ID')),
            ],
        ),
        migrations.AddField(
            model_name='measuementname',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerinfo', verbose_name='Müşteri ID'),
        ),
    ]
