# Generated by Django 4.0.1 on 2022-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_measuementname_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='created_time',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
