# Generated by Django 4.0.1 on 2022-02-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customerinfo_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='measurement_id',
        ),
        migrations.DeleteModel(
            name='MeasuementName',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
