# Generated by Django 4.0.1 on 2022-02-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0010_remove_measurement_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuementName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(max_length=50, verbose_name='Ölçü Adı')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerinfo', verbose_name='Müşteri ID')),
            ],
            options={
                'verbose_name': 'Ölçü Adı',
                'verbose_name_plural': 'Ölçü Adları',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(choices=[('SALON', 'Salon Odası'), ('OO', 'Oturma Odası'), ('MUTFAK', 'Mutfak'), ('YO', 'Yatak Odası'), ('ÇOCUK O', 'Çocuk Odası'), ('Çalışma O', 'Çalışma Odası'), ('GIYINME ODASI', 'Giyinme Odası'), ('SINEMA ODASI', 'Sinema Odası'), ('KILER', 'Kiler'), ('MISAFIR ODASI', 'Misafir Odası')], max_length=15, verbose_name='Oda Adı')),
                ('curtain_type', models.CharField(choices=[('ZEBRA', 'Zebra Perde'), ('STOR', 'Stor Perde'), ('DIKEY', 'Dikey Perde'), ('Plicel', 'Plicel Perde'), ('KUMAS', 'Kumaş Perde'), ('TÜL', 'Tül Perde'), ('FON', 'Fon Perde'), ('GUNESLİK', 'Güneşlik Perde')], max_length=15, verbose_name='Perde Tipi')),
                ('width', models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='En')),
                ('height', models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='Boy')),
                ('note', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ölçü Notu')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerinfo', verbose_name='Müşteri IDs')),
                ('measurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.measuementname', verbose_name='Ölçü ID')),
            ],
            options={
                'verbose_name': 'Ölçü',
                'verbose_name_plural': 'Ölçüler',
            },
        ),
    ]
