# Generated by Django 4.0.1 on 2022-02-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuementname',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='measuementname',
            name='situation',
            field=models.CharField(blank=True, choices=[('Ö Alınmadı', 'Ölçü Alınmadı'), ('Ö Alındı', 'Ölçü Alındı'), ('Ö Alınacak', 'Ölçü Alınacak'), ('S Alınmadı', 'Sipariş Alınmadı'), ('S Alındı', 'Sipariş Alındı'), ('Iptal', 'İptal Edildi'), ('Beklemede', 'Beklemede'), ('O Bekleniyor', 'Ödeme Bekleniyor')], max_length=50, null=True, verbose_name='Durumu'),
        ),
    ]
