# Generated by Django 4.0.2 on 2022-02-19 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Ürün Kategorisi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Firma Adı')),
                ('salesmanan', models.CharField(default='bilinmiyor', max_length=100, verbose_name='Pazaralamacı Adı')),
                ('salesman_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Pazarlamacı Tel')),
                ('order_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Sipariş Hattı')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Firma Personeli')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar ',
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Başlık ismi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firms.firm', verbose_name='Firma Adı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Firma Personeli')),
            ],
            options={
                'verbose_name': 'Başlık',
                'verbose_name_plural': 'Başlıklar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Kodu')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Renk')),
                ('width', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='En')),
                ('max_width', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Max Ayarlanbilir En')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fiyat')),
                ('picture', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firms.firm', verbose_name='Firma adı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firms.categories', verbose_name='Kategorisi')),
                ('head_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firms.head', verbose_name='Başlık Adı')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Varyant Kodu')),
                ('variant_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fiyat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firms.product', verbose_name='Ürün ID')),
            ],
            options={
                'verbose_name': 'Varyant',
                'verbose_name_plural': 'Varyantlar',
            },
        ),
    ]
