# Generated by Django 4.0.2 on 2022-02-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='salesmanan',
            field=models.CharField(max_length=100, verbose_name='Pazaralamacı Adı'),
        ),
    ]
