# Generated by Django 4.0.2 on 2022-02-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_alter_firm_salesmanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
    ]
