# Generated by Django 4.0.2 on 2022-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0003_alter_firm_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='images/window_images', verbose_name='Resim'),
        ),
    ]
