# Generated by Django 4.0.2 on 2022-02-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0006_alter_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='code',
            new_name='variant_code',
        ),
    ]
