# Generated by Django 4.0.2 on 2022-03-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0007_rename_code_variant_variant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_variant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kodu'),
        ),
    ]
