# Generated by Django 4.0.1 on 2022-02-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_measuementname_alter_customerinfo_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ölçü Notu'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
