# Generated by Django 4.0.1 on 2022-02-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_measurement_note_measurement_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measuementname',
            options={'verbose_name': 'Ölçü Adı', 'verbose_name_plural': 'Ölçü Adları'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Ölçü', 'verbose_name_plural': 'Ölçüler'},
        ),
        migrations.AddField(
            model_name='measurement',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='Boy'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='En'),
        ),
    ]
