# Generated by Django 4.0.1 on 2022-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customerinfo_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Üyelik Zamanı'),
        ),
    ]
