# Generated by Django 3.2.12 on 2022-02-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_measuementname_date_measuementname_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuementname',
            name='situation',
            field=models.CharField(blank=True, choices=[('Ö Alınmadı', 'Ölçü Alınmadı'), ('Ö Alındı', 'Ölçü Alındı'), ('Ö Alınacak', 'Ölçü Alınacak'), ('S Alınmadı', 'Sipariş Alınmadı'), ('S Alındı', 'Sipariş Alındı'), ('Iptal', 'İptal Edildi'), ('Beklemede', 'Beklemede'), ('O Bekleniyor', 'Ödeme Bekleniyor')], default='Ö Alınacak', max_length=50, null=True, verbose_name='Durumu'),
        ),
    ]
