# Generated by Django 3.2.12 on 2022-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_measuementname_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='window_picture',
            field=models.FileField(blank=True, null=True, upload_to='images/window_images', verbose_name='Pencere Resmi'),
        ),
    ]
