# Generated by Django 3.2.12 on 2022-02-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_measurement_window_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='window_picture',
            field=models.FileField(upload_to='images/window_images', verbose_name='Pencere Resmi'),
        ),
    ]
